// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = "\nmain :: [rule | comment]+ anyspace* eof ;\n\ncomment :: anyspace* '#' [any ^ eol]* eol ;\n\nrule :: rule#_rule ;\n_rule :: anyspace* .name:id anyspace* '::' [rule_body | true#true] anyspace* ';' ;\n\nrule_body :: group ;\n\ngroup :: or#group_or | and#group_and ;\n\ngroup_or :: token [ anyspace* [['|' token] | not] ]+ ;\ngroup_and :: token [ anyspace token]* ;\n\ntoken :: token#_token ;\n_token :: anyspace* [cap | ast]? [ sub:id | str!str | subgroup | not ] repeater? ;\n\ncap :: .capattr:'.'? .cap:id [':' | .treatstr:'!'] ;\nast :: .ast:id '#' ;\n\nrepeater :: .repeat:_repeater ;\n_repeater :: '+' | '*' | '?' ;\n\nsubgroup :: '[' group anyspace* ']' ;\n\nnot :: not#_not ;\n_not :: '^' token ;\n";

}).call(this);
