// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = "\nmain :: test:type anyspace .id:id blah!\"(\" arg#arg+ \")\" ;\n\n# blah blah blah\n\narg :: type anyspace id ;\n\ntype :: a b [ c | d ^ [ e | f ] ] ;\n";

}).call(this);
